from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

old = '''      if(label.classList.contains('cfg-switch')) return;\n      if(label.querySelector('.cfg-switch-track')) return;\n      label.classList.add('simpla-mobile-switch-row');'''
new = '''      if(label.classList.contains('cfg-switch')) return;\n      if(label.querySelector('.cfg-switch-track')) return;\n      if(label.classList.contains('profissional-servico-item')) {\n        label.classList.remove('simpla-mobile-switch-row');\n        return;\n      }\n      label.classList.add('simpla-mobile-switch-row');\n\n      const textosDiretos = Array.from(label.childNodes).filter(no =>\n        no.nodeType === Node.TEXT_NODE && String(no.textContent || '').trim()\n      );\n      textosDiretos.forEach(no => {\n        const span = document.createElement('span');\n        span.className = 'simpla-mobile-option-text';\n        span.textContent = String(no.textContent || '').trim();\n        no.replaceWith(span);\n      });'''
if old not in s:
    raise SystemExit('Trecho estrutural esperado não encontrado')
s = s.replace(old, new, 1)

marker = '</style>\n<script id="simpla-mobile-config-structural-v3-script">'
css = '''</style>\n<style id="simpla-mobile-config-v4-fix">\n@media (max-width:768px){\n  #configuracoes label.simpla-mobile-switch-row{\n    display:grid!important;\n    grid-template-columns:46px minmax(0,1fr)!important;\n    column-gap:12px!important;\n    align-items:center!important;\n  }\n  #configuracoes label.simpla-mobile-switch-row > input[type="checkbox"]{\n    grid-column:1!important;\n    grid-row:1!important;\n    margin:0!important;\n    justify-self:start!important;\n  }\n  #configuracoes label.simpla-mobile-switch-row > .simpla-mobile-option-text{\n    grid-column:2!important;\n    grid-row:1!important;\n    display:block!important;\n    min-width:0!important;\n    margin:0!important;\n    font-size:11.5px!important;\n    line-height:1.28!important;\n    white-space:normal!important;\n    overflow-wrap:anywhere!important;\n  }\n  #configuracoes .profissional-servico-item{\n    display:grid!important;\n    grid-template-columns:44px minmax(0,1fr) 88px!important;\n    column-gap:12px!important;\n    align-items:center!important;\n    padding:11px!important;\n  }\n  #configuracoes .profissional-servico-item > input[type="checkbox"]{\n    grid-column:1!important;\n    grid-row:1!important;\n    width:40px!important;\n    min-width:40px!important;\n    max-width:40px!important;\n    margin:0!important;\n    justify-self:start!important;\n  }\n  #configuracoes .profissional-servico-item > span{\n    grid-column:2!important;\n    grid-row:1!important;\n    min-width:0!important;\n    margin:0!important;\n    padding:0!important;\n    font-size:11.5px!important;\n    line-height:1.22!important;\n  }\n  #configuracoes .profissional-servico-item > span b{\n    display:block!important;\n    font-size:12px!important;\n    line-height:1.18!important;\n    margin-bottom:2px!important;\n  }\n  #configuracoes .profissional-servico-item > span small{\n    display:block!important;\n    font-size:10.5px!important;\n    line-height:1.18!important;\n  }\n  #configuracoes .profissional-servico-item > input[type="number"]{\n    grid-column:3!important;\n    grid-row:1!important;\n    width:88px!important;\n    min-width:88px!important;\n    max-width:88px!important;\n    padding:8px 7px!important;\n    font-size:14px!important;\n    text-align:center!important;\n  }\n}\n@media (max-width:420px){\n  #configuracoes label.simpla-mobile-switch-row{\n    grid-template-columns:42px minmax(0,1fr)!important;\n    column-gap:10px!important;\n  }\n  #configuracoes label.simpla-mobile-switch-row > .simpla-mobile-option-text{\n    font-size:11px!important;\n  }\n  #configuracoes .profissional-servico-item{\n    grid-template-columns:42px minmax(0,1fr) 84px!important;\n    column-gap:10px!important;\n    padding:10px!important;\n  }\n  #configuracoes .profissional-servico-item > input[type="number"]{\n    width:84px!important;min-width:84px!important;max-width:84px!important;\n  }\n}\n</style>\n<script id="simpla-mobile-config-structural-v3-script">'''
if marker not in s:
    raise SystemExit('Marcador de script estrutural não encontrado')
s = s.replace(marker, css, 1)

p.write_text(s, encoding='utf-8')
